### ISSUE TITLE
Backend apis

### ISSUE THREAD

**Issue by khandelwal-arpit** [omob/LMS-FRONTEND#1]
Hi Omob,

Thanks for sharing this project. I wanted tor run it locally or from the heroku link you have shared however the credentials to login into the app are not mentioned in your documentation. Can you please share a sample userid/pwd for login into this app?

Also, can you share the backend api code which we can run locally to run this full stack application. Thanks in advance and Awesome work!

**Comment by omob** [comment]
Hello Arpit

Thanks for reaching out and your interest in the project. Please be informed the **Readme** file has been updated with the requested credentials.

Also, see below URL for the backend API Code as requested.
https://github.com/omob/LMS-Backend-API

Do let me know if you have any queries.

Regards
