### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by matheus-arruda** [omob/LMS-FRONTEND#23]
Hello, has the project been abandoned?
If possible could you provide a backup of the database? or a user input template in json format?

**Comment by omob** [comment]
Hello Matheus

No update has been carried out on the project for a while now.

Click the below link to access a copy of the database collections.
https://1drv.ms/u/s!AtuFwKw_48h8qUm0OLgfTB264g2p?e=dx2X2w

Cheers!

**Comment by matheus-arruda** [comment]
Thankss!!
